#  mvn clean install -Dspring.profiles.active=dev
spring:
  jpa:
    hibernate:
      ddl-auto: create
  cloud:
    discovery:
      enabled: true
#  l'URL du serveur Eureka auquel l'application doit s'enregistrer. Service "discovery" dans Docker Compose
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka} #http://discovery:8761/eureka/
