#  mvn clean install -Dspring.profiles.active=dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/bills-db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

#podman run --name bills-db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=bills-db -e MYSQL_USER=admin -e MYSQL_PASSWORD=root -p 3308:3306 -d mysql:latest
