#  mvn clean install -Dspring.profiles.active=dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customers-db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always

#docker run --name customers-db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=customers-db -e MYSQL_USER=admin -e MYSQL_PASSWORD=root -p 3306:3306 -d mysql:latest